/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUserAccountRouteImport } from './routes/_layout/user-account'
import { Route as LayoutSpecimensRouteImport } from './routes/_layout/specimens'
import { Route as LayoutResultsRouteImport } from './routes/_layout/results'
import { Route as LayoutPatientsRouteImport } from './routes/_layout/patients'
import { Route as LayoutOrdersRouteImport } from './routes/_layout/orders'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutInvoicesRouteImport } from './routes/_layout/invoices'
import { Route as LayoutDoctorsRouteImport } from './routes/_layout/doctors'
import { Route as LayoutDoctorCommissionPaymentsRouteImport } from './routes/_layout/doctor-commission-payments'
import { Route as LayoutConfigurationsRouteImport } from './routes/_layout/configurations'
import { Route as LayoutCommissionsRouteImport } from './routes/_layout/commissions'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutResultsIndexRouteImport } from './routes/_layout/results/index'
import { Route as LayoutPatientsIndexRouteImport } from './routes/_layout/patients/index'
import { Route as LayoutOrdersIndexRouteImport } from './routes/_layout/orders/index'
import { Route as LayoutInvoicesIndexRouteImport } from './routes/_layout/invoices/index'
import { Route as LayoutDoctorsIndexRouteImport } from './routes/_layout/doctors/index'
import { Route as LayoutDoctorCommissionPaymentsIndexRouteImport } from './routes/_layout/doctor-commission-payments/index'
import { Route as LayoutConfigurationsIndexRouteImport } from './routes/_layout/configurations/index'
import { Route as LayoutCommissionsIndexRouteImport } from './routes/_layout/commissions/index'
import { Route as LayoutResultsOrderIdRouteImport } from './routes/_layout/results/$orderId'
import { Route as LayoutPatientsPatientIdRouteImport } from './routes/_layout/patients/$patientId'
import { Route as LayoutOrdersNewRouteImport } from './routes/_layout/orders/new'
import { Route as LayoutOrdersOrderIdRouteImport } from './routes/_layout/orders/$orderId'
import { Route as LayoutInvoicesInvoiceIdRouteImport } from './routes/_layout/invoices/$invoiceId'
import { Route as LayoutDoctorsDoctorIdRouteImport } from './routes/_layout/doctors/$doctorId'
import { Route as LayoutDoctorCommissionPaymentsNewRouteImport } from './routes/_layout/doctor-commission-payments/new'
import { Route as LayoutDoctorCommissionPaymentsPaymentIdRouteImport } from './routes/_layout/doctor-commission-payments/$paymentId'
import { Route as LayoutConfigurationsUsersRouteImport } from './routes/_layout/configurations/users'
import { Route as LayoutConfigurationsUnitesRouteImport } from './routes/_layout/configurations/unites'
import { Route as LayoutConfigurationsTypesPrelevementRouteImport } from './routes/_layout/configurations/types-prelevement'
import { Route as LayoutConfigurationsTitresRouteImport } from './routes/_layout/configurations/titres'
import { Route as LayoutConfigurationsTarifsAssuranceRouteImport } from './routes/_layout/configurations/tarifs-assurance'
import { Route as LayoutConfigurationsRolesRouteImport } from './routes/_layout/configurations/roles'
import { Route as LayoutConfigurationsReglesValidationRouteImport } from './routes/_layout/configurations/regles-validation'
import { Route as LayoutConfigurationsReglesAutomatiseesRouteImport } from './routes/_layout/configurations/regles-automatisees'
import { Route as LayoutConfigurationsRapportsRouteImport } from './routes/_layout/configurations/rapports'
import { Route as LayoutConfigurationsPermissionsRouteImport } from './routes/_layout/configurations/permissions'
import { Route as LayoutConfigurationsMotifsRejetRouteImport } from './routes/_layout/configurations/motifs-rejet'
import { Route as LayoutConfigurationsMethodesPaiementRouteImport } from './routes/_layout/configurations/methodes-paiement'
import { Route as LayoutConfigurationsLaboratoireRouteImport } from './routes/_layout/configurations/laboratoire'
import { Route as LayoutConfigurationsFinanceRouteImport } from './routes/_layout/configurations/finance'
import { Route as LayoutConfigurationsContextsPatientRouteImport } from './routes/_layout/configurations/contexts-patient'
import { Route as LayoutConfigurationsCategoriesRouteImport } from './routes/_layout/configurations/categories'
import { Route as LayoutConfigurationsCatalogueRouteImport } from './routes/_layout/configurations/catalogue'
import { Route as LayoutConfigurationsAuditRouteImport } from './routes/_layout/configurations/audit'
import { Route as LayoutConfigurationsAssureursRouteImport } from './routes/_layout/configurations/assureurs'
import { Route as LayoutConfigurationsAnalytesRouteImport } from './routes/_layout/configurations/analytes'
import { Route as LayoutCommissionsEntriesRouteImport } from './routes/_layout/commissions/entries'
import { Route as LayoutOrdersOrderIdIndexRouteImport } from './routes/_layout/orders/$orderId/index'
import { Route as LayoutCommissionsPaymentsIndexRouteImport } from './routes/_layout/commissions/payments/index'
import { Route as LayoutOrdersOrderIdReportRouteImport } from './routes/_layout/orders/$orderId/report'
import { Route as LayoutOrdersOrderIdEditRouteImport } from './routes/_layout/orders/$orderId/edit'
import { Route as LayoutCommissionsPaymentsNewRouteImport } from './routes/_layout/commissions/payments/new'
import { Route as LayoutCommissionsPaymentsPaymentIdRouteImport } from './routes/_layout/commissions/payments/$paymentId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUserAccountRoute = LayoutUserAccountRouteImport.update({
  id: '/user-account',
  path: '/user-account',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSpecimensRoute = LayoutSpecimensRouteImport.update({
  id: '/specimens',
  path: '/specimens',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResultsRoute = LayoutResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPatientsRoute = LayoutPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersRoute = LayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInvoicesRoute = LayoutInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDoctorsRoute = LayoutDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDoctorCommissionPaymentsRoute =
  LayoutDoctorCommissionPaymentsRouteImport.update({
    id: '/doctor-commission-payments',
    path: '/doctor-commission-payments',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutConfigurationsRoute = LayoutConfigurationsRouteImport.update({
  id: '/configurations',
  path: '/configurations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCommissionsRoute = LayoutCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResultsIndexRoute = LayoutResultsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutResultsRoute,
} as any)
const LayoutPatientsIndexRoute = LayoutPatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPatientsRoute,
} as any)
const LayoutOrdersIndexRoute = LayoutOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutOrdersRoute,
} as any)
const LayoutInvoicesIndexRoute = LayoutInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutInvoicesRoute,
} as any)
const LayoutDoctorsIndexRoute = LayoutDoctorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutDoctorsRoute,
} as any)
const LayoutDoctorCommissionPaymentsIndexRoute =
  LayoutDoctorCommissionPaymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutDoctorCommissionPaymentsRoute,
  } as any)
const LayoutConfigurationsIndexRoute =
  LayoutConfigurationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutCommissionsIndexRoute = LayoutCommissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutCommissionsRoute,
} as any)
const LayoutResultsOrderIdRoute = LayoutResultsOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => LayoutResultsRoute,
} as any)
const LayoutPatientsPatientIdRoute = LayoutPatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => LayoutPatientsRoute,
} as any)
const LayoutOrdersNewRoute = LayoutOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutOrdersRoute,
} as any)
const LayoutOrdersOrderIdRoute = LayoutOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => LayoutOrdersRoute,
} as any)
const LayoutInvoicesInvoiceIdRoute = LayoutInvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => LayoutInvoicesRoute,
} as any)
const LayoutDoctorsDoctorIdRoute = LayoutDoctorsDoctorIdRouteImport.update({
  id: '/$doctorId',
  path: '/$doctorId',
  getParentRoute: () => LayoutDoctorsRoute,
} as any)
const LayoutDoctorCommissionPaymentsNewRoute =
  LayoutDoctorCommissionPaymentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => LayoutDoctorCommissionPaymentsRoute,
  } as any)
const LayoutDoctorCommissionPaymentsPaymentIdRoute =
  LayoutDoctorCommissionPaymentsPaymentIdRouteImport.update({
    id: '/$paymentId',
    path: '/$paymentId',
    getParentRoute: () => LayoutDoctorCommissionPaymentsRoute,
  } as any)
const LayoutConfigurationsUsersRoute =
  LayoutConfigurationsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsUnitesRoute =
  LayoutConfigurationsUnitesRouteImport.update({
    id: '/unites',
    path: '/unites',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsTypesPrelevementRoute =
  LayoutConfigurationsTypesPrelevementRouteImport.update({
    id: '/types-prelevement',
    path: '/types-prelevement',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsTitresRoute =
  LayoutConfigurationsTitresRouteImport.update({
    id: '/titres',
    path: '/titres',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsTarifsAssuranceRoute =
  LayoutConfigurationsTarifsAssuranceRouteImport.update({
    id: '/tarifs-assurance',
    path: '/tarifs-assurance',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsRolesRoute =
  LayoutConfigurationsRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsReglesValidationRoute =
  LayoutConfigurationsReglesValidationRouteImport.update({
    id: '/regles-validation',
    path: '/regles-validation',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsReglesAutomatiseesRoute =
  LayoutConfigurationsReglesAutomatiseesRouteImport.update({
    id: '/regles-automatisees',
    path: '/regles-automatisees',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsRapportsRoute =
  LayoutConfigurationsRapportsRouteImport.update({
    id: '/rapports',
    path: '/rapports',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsPermissionsRoute =
  LayoutConfigurationsPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsMotifsRejetRoute =
  LayoutConfigurationsMotifsRejetRouteImport.update({
    id: '/motifs-rejet',
    path: '/motifs-rejet',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsMethodesPaiementRoute =
  LayoutConfigurationsMethodesPaiementRouteImport.update({
    id: '/methodes-paiement',
    path: '/methodes-paiement',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsLaboratoireRoute =
  LayoutConfigurationsLaboratoireRouteImport.update({
    id: '/laboratoire',
    path: '/laboratoire',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsFinanceRoute =
  LayoutConfigurationsFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsContextsPatientRoute =
  LayoutConfigurationsContextsPatientRouteImport.update({
    id: '/contexts-patient',
    path: '/contexts-patient',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsCategoriesRoute =
  LayoutConfigurationsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsCatalogueRoute =
  LayoutConfigurationsCatalogueRouteImport.update({
    id: '/catalogue',
    path: '/catalogue',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsAuditRoute =
  LayoutConfigurationsAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsAssureursRoute =
  LayoutConfigurationsAssureursRouteImport.update({
    id: '/assureurs',
    path: '/assureurs',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutConfigurationsAnalytesRoute =
  LayoutConfigurationsAnalytesRouteImport.update({
    id: '/analytes',
    path: '/analytes',
    getParentRoute: () => LayoutConfigurationsRoute,
  } as any)
const LayoutCommissionsEntriesRoute =
  LayoutCommissionsEntriesRouteImport.update({
    id: '/entries',
    path: '/entries',
    getParentRoute: () => LayoutCommissionsRoute,
  } as any)
const LayoutOrdersOrderIdIndexRoute =
  LayoutOrdersOrderIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutOrdersOrderIdRoute,
  } as any)
const LayoutCommissionsPaymentsIndexRoute =
  LayoutCommissionsPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => LayoutCommissionsRoute,
  } as any)
const LayoutOrdersOrderIdReportRoute =
  LayoutOrdersOrderIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => LayoutOrdersOrderIdRoute,
  } as any)
const LayoutOrdersOrderIdEditRoute = LayoutOrdersOrderIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LayoutOrdersOrderIdRoute,
} as any)
const LayoutCommissionsPaymentsNewRoute =
  LayoutCommissionsPaymentsNewRouteImport.update({
    id: '/payments/new',
    path: '/payments/new',
    getParentRoute: () => LayoutCommissionsRoute,
  } as any)
const LayoutCommissionsPaymentsPaymentIdRoute =
  LayoutCommissionsPaymentsPaymentIdRouteImport.update({
    id: '/payments/$paymentId',
    path: '/payments/$paymentId',
    getParentRoute: () => LayoutCommissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRoute
  '/commissions': typeof LayoutCommissionsRouteWithChildren
  '/configurations': typeof LayoutConfigurationsRouteWithChildren
  '/doctor-commission-payments': typeof LayoutDoctorCommissionPaymentsRouteWithChildren
  '/doctors': typeof LayoutDoctorsRouteWithChildren
  '/invoices': typeof LayoutInvoicesRouteWithChildren
  '/items': typeof LayoutItemsRoute
  '/orders': typeof LayoutOrdersRouteWithChildren
  '/patients': typeof LayoutPatientsRouteWithChildren
  '/results': typeof LayoutResultsRouteWithChildren
  '/specimens': typeof LayoutSpecimensRoute
  '/user-account': typeof LayoutUserAccountRoute
  '/commissions/entries': typeof LayoutCommissionsEntriesRoute
  '/configurations/analytes': typeof LayoutConfigurationsAnalytesRoute
  '/configurations/assureurs': typeof LayoutConfigurationsAssureursRoute
  '/configurations/audit': typeof LayoutConfigurationsAuditRoute
  '/configurations/catalogue': typeof LayoutConfigurationsCatalogueRoute
  '/configurations/categories': typeof LayoutConfigurationsCategoriesRoute
  '/configurations/contexts-patient': typeof LayoutConfigurationsContextsPatientRoute
  '/configurations/finance': typeof LayoutConfigurationsFinanceRoute
  '/configurations/laboratoire': typeof LayoutConfigurationsLaboratoireRoute
  '/configurations/methodes-paiement': typeof LayoutConfigurationsMethodesPaiementRoute
  '/configurations/motifs-rejet': typeof LayoutConfigurationsMotifsRejetRoute
  '/configurations/permissions': typeof LayoutConfigurationsPermissionsRoute
  '/configurations/rapports': typeof LayoutConfigurationsRapportsRoute
  '/configurations/regles-automatisees': typeof LayoutConfigurationsReglesAutomatiseesRoute
  '/configurations/regles-validation': typeof LayoutConfigurationsReglesValidationRoute
  '/configurations/roles': typeof LayoutConfigurationsRolesRoute
  '/configurations/tarifs-assurance': typeof LayoutConfigurationsTarifsAssuranceRoute
  '/configurations/titres': typeof LayoutConfigurationsTitresRoute
  '/configurations/types-prelevement': typeof LayoutConfigurationsTypesPrelevementRoute
  '/configurations/unites': typeof LayoutConfigurationsUnitesRoute
  '/configurations/users': typeof LayoutConfigurationsUsersRoute
  '/doctor-commission-payments/$paymentId': typeof LayoutDoctorCommissionPaymentsPaymentIdRoute
  '/doctor-commission-payments/new': typeof LayoutDoctorCommissionPaymentsNewRoute
  '/doctors/$doctorId': typeof LayoutDoctorsDoctorIdRoute
  '/invoices/$invoiceId': typeof LayoutInvoicesInvoiceIdRoute
  '/orders/$orderId': typeof LayoutOrdersOrderIdRouteWithChildren
  '/orders/new': typeof LayoutOrdersNewRoute
  '/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/results/$orderId': typeof LayoutResultsOrderIdRoute
  '/commissions/': typeof LayoutCommissionsIndexRoute
  '/configurations/': typeof LayoutConfigurationsIndexRoute
  '/doctor-commission-payments/': typeof LayoutDoctorCommissionPaymentsIndexRoute
  '/doctors/': typeof LayoutDoctorsIndexRoute
  '/invoices/': typeof LayoutInvoicesIndexRoute
  '/orders/': typeof LayoutOrdersIndexRoute
  '/patients/': typeof LayoutPatientsIndexRoute
  '/results/': typeof LayoutResultsIndexRoute
  '/commissions/payments/$paymentId': typeof LayoutCommissionsPaymentsPaymentIdRoute
  '/commissions/payments/new': typeof LayoutCommissionsPaymentsNewRoute
  '/orders/$orderId/edit': typeof LayoutOrdersOrderIdEditRoute
  '/orders/$orderId/report': typeof LayoutOrdersOrderIdReportRoute
  '/commissions/payments/': typeof LayoutCommissionsPaymentsIndexRoute
  '/orders/$orderId/': typeof LayoutOrdersOrderIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/specimens': typeof LayoutSpecimensRoute
  '/user-account': typeof LayoutUserAccountRoute
  '/': typeof LayoutIndexRoute
  '/commissions/entries': typeof LayoutCommissionsEntriesRoute
  '/configurations/analytes': typeof LayoutConfigurationsAnalytesRoute
  '/configurations/assureurs': typeof LayoutConfigurationsAssureursRoute
  '/configurations/audit': typeof LayoutConfigurationsAuditRoute
  '/configurations/catalogue': typeof LayoutConfigurationsCatalogueRoute
  '/configurations/categories': typeof LayoutConfigurationsCategoriesRoute
  '/configurations/contexts-patient': typeof LayoutConfigurationsContextsPatientRoute
  '/configurations/finance': typeof LayoutConfigurationsFinanceRoute
  '/configurations/laboratoire': typeof LayoutConfigurationsLaboratoireRoute
  '/configurations/methodes-paiement': typeof LayoutConfigurationsMethodesPaiementRoute
  '/configurations/motifs-rejet': typeof LayoutConfigurationsMotifsRejetRoute
  '/configurations/permissions': typeof LayoutConfigurationsPermissionsRoute
  '/configurations/rapports': typeof LayoutConfigurationsRapportsRoute
  '/configurations/regles-automatisees': typeof LayoutConfigurationsReglesAutomatiseesRoute
  '/configurations/regles-validation': typeof LayoutConfigurationsReglesValidationRoute
  '/configurations/roles': typeof LayoutConfigurationsRolesRoute
  '/configurations/tarifs-assurance': typeof LayoutConfigurationsTarifsAssuranceRoute
  '/configurations/titres': typeof LayoutConfigurationsTitresRoute
  '/configurations/types-prelevement': typeof LayoutConfigurationsTypesPrelevementRoute
  '/configurations/unites': typeof LayoutConfigurationsUnitesRoute
  '/configurations/users': typeof LayoutConfigurationsUsersRoute
  '/doctor-commission-payments/$paymentId': typeof LayoutDoctorCommissionPaymentsPaymentIdRoute
  '/doctor-commission-payments/new': typeof LayoutDoctorCommissionPaymentsNewRoute
  '/doctors/$doctorId': typeof LayoutDoctorsDoctorIdRoute
  '/invoices/$invoiceId': typeof LayoutInvoicesInvoiceIdRoute
  '/orders/new': typeof LayoutOrdersNewRoute
  '/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/results/$orderId': typeof LayoutResultsOrderIdRoute
  '/commissions': typeof LayoutCommissionsIndexRoute
  '/configurations': typeof LayoutConfigurationsIndexRoute
  '/doctor-commission-payments': typeof LayoutDoctorCommissionPaymentsIndexRoute
  '/doctors': typeof LayoutDoctorsIndexRoute
  '/invoices': typeof LayoutInvoicesIndexRoute
  '/orders': typeof LayoutOrdersIndexRoute
  '/patients': typeof LayoutPatientsIndexRoute
  '/results': typeof LayoutResultsIndexRoute
  '/commissions/payments/$paymentId': typeof LayoutCommissionsPaymentsPaymentIdRoute
  '/commissions/payments/new': typeof LayoutCommissionsPaymentsNewRoute
  '/orders/$orderId/edit': typeof LayoutOrdersOrderIdEditRoute
  '/orders/$orderId/report': typeof LayoutOrdersOrderIdReportRoute
  '/commissions/payments': typeof LayoutCommissionsPaymentsIndexRoute
  '/orders/$orderId': typeof LayoutOrdersOrderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/commissions': typeof LayoutCommissionsRouteWithChildren
  '/_layout/configurations': typeof LayoutConfigurationsRouteWithChildren
  '/_layout/doctor-commission-payments': typeof LayoutDoctorCommissionPaymentsRouteWithChildren
  '/_layout/doctors': typeof LayoutDoctorsRouteWithChildren
  '/_layout/invoices': typeof LayoutInvoicesRouteWithChildren
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/orders': typeof LayoutOrdersRouteWithChildren
  '/_layout/patients': typeof LayoutPatientsRouteWithChildren
  '/_layout/results': typeof LayoutResultsRouteWithChildren
  '/_layout/specimens': typeof LayoutSpecimensRoute
  '/_layout/user-account': typeof LayoutUserAccountRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/commissions/entries': typeof LayoutCommissionsEntriesRoute
  '/_layout/configurations/analytes': typeof LayoutConfigurationsAnalytesRoute
  '/_layout/configurations/assureurs': typeof LayoutConfigurationsAssureursRoute
  '/_layout/configurations/audit': typeof LayoutConfigurationsAuditRoute
  '/_layout/configurations/catalogue': typeof LayoutConfigurationsCatalogueRoute
  '/_layout/configurations/categories': typeof LayoutConfigurationsCategoriesRoute
  '/_layout/configurations/contexts-patient': typeof LayoutConfigurationsContextsPatientRoute
  '/_layout/configurations/finance': typeof LayoutConfigurationsFinanceRoute
  '/_layout/configurations/laboratoire': typeof LayoutConfigurationsLaboratoireRoute
  '/_layout/configurations/methodes-paiement': typeof LayoutConfigurationsMethodesPaiementRoute
  '/_layout/configurations/motifs-rejet': typeof LayoutConfigurationsMotifsRejetRoute
  '/_layout/configurations/permissions': typeof LayoutConfigurationsPermissionsRoute
  '/_layout/configurations/rapports': typeof LayoutConfigurationsRapportsRoute
  '/_layout/configurations/regles-automatisees': typeof LayoutConfigurationsReglesAutomatiseesRoute
  '/_layout/configurations/regles-validation': typeof LayoutConfigurationsReglesValidationRoute
  '/_layout/configurations/roles': typeof LayoutConfigurationsRolesRoute
  '/_layout/configurations/tarifs-assurance': typeof LayoutConfigurationsTarifsAssuranceRoute
  '/_layout/configurations/titres': typeof LayoutConfigurationsTitresRoute
  '/_layout/configurations/types-prelevement': typeof LayoutConfigurationsTypesPrelevementRoute
  '/_layout/configurations/unites': typeof LayoutConfigurationsUnitesRoute
  '/_layout/configurations/users': typeof LayoutConfigurationsUsersRoute
  '/_layout/doctor-commission-payments/$paymentId': typeof LayoutDoctorCommissionPaymentsPaymentIdRoute
  '/_layout/doctor-commission-payments/new': typeof LayoutDoctorCommissionPaymentsNewRoute
  '/_layout/doctors/$doctorId': typeof LayoutDoctorsDoctorIdRoute
  '/_layout/invoices/$invoiceId': typeof LayoutInvoicesInvoiceIdRoute
  '/_layout/orders/$orderId': typeof LayoutOrdersOrderIdRouteWithChildren
  '/_layout/orders/new': typeof LayoutOrdersNewRoute
  '/_layout/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/_layout/results/$orderId': typeof LayoutResultsOrderIdRoute
  '/_layout/commissions/': typeof LayoutCommissionsIndexRoute
  '/_layout/configurations/': typeof LayoutConfigurationsIndexRoute
  '/_layout/doctor-commission-payments/': typeof LayoutDoctorCommissionPaymentsIndexRoute
  '/_layout/doctors/': typeof LayoutDoctorsIndexRoute
  '/_layout/invoices/': typeof LayoutInvoicesIndexRoute
  '/_layout/orders/': typeof LayoutOrdersIndexRoute
  '/_layout/patients/': typeof LayoutPatientsIndexRoute
  '/_layout/results/': typeof LayoutResultsIndexRoute
  '/_layout/commissions/payments/$paymentId': typeof LayoutCommissionsPaymentsPaymentIdRoute
  '/_layout/commissions/payments/new': typeof LayoutCommissionsPaymentsNewRoute
  '/_layout/orders/$orderId/edit': typeof LayoutOrdersOrderIdEditRoute
  '/_layout/orders/$orderId/report': typeof LayoutOrdersOrderIdReportRoute
  '/_layout/commissions/payments/': typeof LayoutCommissionsPaymentsIndexRoute
  '/_layout/orders/$orderId/': typeof LayoutOrdersOrderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/commissions'
    | '/configurations'
    | '/doctor-commission-payments'
    | '/doctors'
    | '/invoices'
    | '/items'
    | '/orders'
    | '/patients'
    | '/results'
    | '/specimens'
    | '/user-account'
    | '/commissions/entries'
    | '/configurations/analytes'
    | '/configurations/assureurs'
    | '/configurations/audit'
    | '/configurations/catalogue'
    | '/configurations/categories'
    | '/configurations/contexts-patient'
    | '/configurations/finance'
    | '/configurations/laboratoire'
    | '/configurations/methodes-paiement'
    | '/configurations/motifs-rejet'
    | '/configurations/permissions'
    | '/configurations/rapports'
    | '/configurations/regles-automatisees'
    | '/configurations/regles-validation'
    | '/configurations/roles'
    | '/configurations/tarifs-assurance'
    | '/configurations/titres'
    | '/configurations/types-prelevement'
    | '/configurations/unites'
    | '/configurations/users'
    | '/doctor-commission-payments/$paymentId'
    | '/doctor-commission-payments/new'
    | '/doctors/$doctorId'
    | '/invoices/$invoiceId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/patients/$patientId'
    | '/results/$orderId'
    | '/commissions/'
    | '/configurations/'
    | '/doctor-commission-payments/'
    | '/doctors/'
    | '/invoices/'
    | '/orders/'
    | '/patients/'
    | '/results/'
    | '/commissions/payments/$paymentId'
    | '/commissions/payments/new'
    | '/orders/$orderId/edit'
    | '/orders/$orderId/report'
    | '/commissions/payments/'
    | '/orders/$orderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/items'
    | '/specimens'
    | '/user-account'
    | '/'
    | '/commissions/entries'
    | '/configurations/analytes'
    | '/configurations/assureurs'
    | '/configurations/audit'
    | '/configurations/catalogue'
    | '/configurations/categories'
    | '/configurations/contexts-patient'
    | '/configurations/finance'
    | '/configurations/laboratoire'
    | '/configurations/methodes-paiement'
    | '/configurations/motifs-rejet'
    | '/configurations/permissions'
    | '/configurations/rapports'
    | '/configurations/regles-automatisees'
    | '/configurations/regles-validation'
    | '/configurations/roles'
    | '/configurations/tarifs-assurance'
    | '/configurations/titres'
    | '/configurations/types-prelevement'
    | '/configurations/unites'
    | '/configurations/users'
    | '/doctor-commission-payments/$paymentId'
    | '/doctor-commission-payments/new'
    | '/doctors/$doctorId'
    | '/invoices/$invoiceId'
    | '/orders/new'
    | '/patients/$patientId'
    | '/results/$orderId'
    | '/commissions'
    | '/configurations'
    | '/doctor-commission-payments'
    | '/doctors'
    | '/invoices'
    | '/orders'
    | '/patients'
    | '/results'
    | '/commissions/payments/$paymentId'
    | '/commissions/payments/new'
    | '/orders/$orderId/edit'
    | '/orders/$orderId/report'
    | '/commissions/payments'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/_layout/admin'
    | '/_layout/commissions'
    | '/_layout/configurations'
    | '/_layout/doctor-commission-payments'
    | '/_layout/doctors'
    | '/_layout/invoices'
    | '/_layout/items'
    | '/_layout/orders'
    | '/_layout/patients'
    | '/_layout/results'
    | '/_layout/specimens'
    | '/_layout/user-account'
    | '/_layout/'
    | '/_layout/commissions/entries'
    | '/_layout/configurations/analytes'
    | '/_layout/configurations/assureurs'
    | '/_layout/configurations/audit'
    | '/_layout/configurations/catalogue'
    | '/_layout/configurations/categories'
    | '/_layout/configurations/contexts-patient'
    | '/_layout/configurations/finance'
    | '/_layout/configurations/laboratoire'
    | '/_layout/configurations/methodes-paiement'
    | '/_layout/configurations/motifs-rejet'
    | '/_layout/configurations/permissions'
    | '/_layout/configurations/rapports'
    | '/_layout/configurations/regles-automatisees'
    | '/_layout/configurations/regles-validation'
    | '/_layout/configurations/roles'
    | '/_layout/configurations/tarifs-assurance'
    | '/_layout/configurations/titres'
    | '/_layout/configurations/types-prelevement'
    | '/_layout/configurations/unites'
    | '/_layout/configurations/users'
    | '/_layout/doctor-commission-payments/$paymentId'
    | '/_layout/doctor-commission-payments/new'
    | '/_layout/doctors/$doctorId'
    | '/_layout/invoices/$invoiceId'
    | '/_layout/orders/$orderId'
    | '/_layout/orders/new'
    | '/_layout/patients/$patientId'
    | '/_layout/results/$orderId'
    | '/_layout/commissions/'
    | '/_layout/configurations/'
    | '/_layout/doctor-commission-payments/'
    | '/_layout/doctors/'
    | '/_layout/invoices/'
    | '/_layout/orders/'
    | '/_layout/patients/'
    | '/_layout/results/'
    | '/_layout/commissions/payments/$paymentId'
    | '/_layout/commissions/payments/new'
    | '/_layout/orders/$orderId/edit'
    | '/_layout/orders/$orderId/report'
    | '/_layout/commissions/payments/'
    | '/_layout/orders/$orderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/user-account': {
      id: '/_layout/user-account'
      path: '/user-account'
      fullPath: '/user-account'
      preLoaderRoute: typeof LayoutUserAccountRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/specimens': {
      id: '/_layout/specimens'
      path: '/specimens'
      fullPath: '/specimens'
      preLoaderRoute: typeof LayoutSpecimensRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/results': {
      id: '/_layout/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof LayoutResultsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/patients': {
      id: '/_layout/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof LayoutPatientsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders': {
      id: '/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invoices': {
      id: '/_layout/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof LayoutInvoicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/doctors': {
      id: '/_layout/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof LayoutDoctorsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/doctor-commission-payments': {
      id: '/_layout/doctor-commission-payments'
      path: '/doctor-commission-payments'
      fullPath: '/doctor-commission-payments'
      preLoaderRoute: typeof LayoutDoctorCommissionPaymentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/configurations': {
      id: '/_layout/configurations'
      path: '/configurations'
      fullPath: '/configurations'
      preLoaderRoute: typeof LayoutConfigurationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/commissions': {
      id: '/_layout/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof LayoutCommissionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/results/': {
      id: '/_layout/results/'
      path: '/'
      fullPath: '/results/'
      preLoaderRoute: typeof LayoutResultsIndexRouteImport
      parentRoute: typeof LayoutResultsRoute
    }
    '/_layout/patients/': {
      id: '/_layout/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof LayoutPatientsIndexRouteImport
      parentRoute: typeof LayoutPatientsRoute
    }
    '/_layout/orders/': {
      id: '/_layout/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof LayoutOrdersIndexRouteImport
      parentRoute: typeof LayoutOrdersRoute
    }
    '/_layout/invoices/': {
      id: '/_layout/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof LayoutInvoicesIndexRouteImport
      parentRoute: typeof LayoutInvoicesRoute
    }
    '/_layout/doctors/': {
      id: '/_layout/doctors/'
      path: '/'
      fullPath: '/doctors/'
      preLoaderRoute: typeof LayoutDoctorsIndexRouteImport
      parentRoute: typeof LayoutDoctorsRoute
    }
    '/_layout/doctor-commission-payments/': {
      id: '/_layout/doctor-commission-payments/'
      path: '/'
      fullPath: '/doctor-commission-payments/'
      preLoaderRoute: typeof LayoutDoctorCommissionPaymentsIndexRouteImport
      parentRoute: typeof LayoutDoctorCommissionPaymentsRoute
    }
    '/_layout/configurations/': {
      id: '/_layout/configurations/'
      path: '/'
      fullPath: '/configurations/'
      preLoaderRoute: typeof LayoutConfigurationsIndexRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/commissions/': {
      id: '/_layout/commissions/'
      path: '/'
      fullPath: '/commissions/'
      preLoaderRoute: typeof LayoutCommissionsIndexRouteImport
      parentRoute: typeof LayoutCommissionsRoute
    }
    '/_layout/results/$orderId': {
      id: '/_layout/results/$orderId'
      path: '/$orderId'
      fullPath: '/results/$orderId'
      preLoaderRoute: typeof LayoutResultsOrderIdRouteImport
      parentRoute: typeof LayoutResultsRoute
    }
    '/_layout/patients/$patientId': {
      id: '/_layout/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof LayoutPatientsPatientIdRouteImport
      parentRoute: typeof LayoutPatientsRoute
    }
    '/_layout/orders/new': {
      id: '/_layout/orders/new'
      path: '/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof LayoutOrdersNewRouteImport
      parentRoute: typeof LayoutOrdersRoute
    }
    '/_layout/orders/$orderId': {
      id: '/_layout/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof LayoutOrdersOrderIdRouteImport
      parentRoute: typeof LayoutOrdersRoute
    }
    '/_layout/invoices/$invoiceId': {
      id: '/_layout/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof LayoutInvoicesInvoiceIdRouteImport
      parentRoute: typeof LayoutInvoicesRoute
    }
    '/_layout/doctors/$doctorId': {
      id: '/_layout/doctors/$doctorId'
      path: '/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof LayoutDoctorsDoctorIdRouteImport
      parentRoute: typeof LayoutDoctorsRoute
    }
    '/_layout/doctor-commission-payments/new': {
      id: '/_layout/doctor-commission-payments/new'
      path: '/new'
      fullPath: '/doctor-commission-payments/new'
      preLoaderRoute: typeof LayoutDoctorCommissionPaymentsNewRouteImport
      parentRoute: typeof LayoutDoctorCommissionPaymentsRoute
    }
    '/_layout/doctor-commission-payments/$paymentId': {
      id: '/_layout/doctor-commission-payments/$paymentId'
      path: '/$paymentId'
      fullPath: '/doctor-commission-payments/$paymentId'
      preLoaderRoute: typeof LayoutDoctorCommissionPaymentsPaymentIdRouteImport
      parentRoute: typeof LayoutDoctorCommissionPaymentsRoute
    }
    '/_layout/configurations/users': {
      id: '/_layout/configurations/users'
      path: '/users'
      fullPath: '/configurations/users'
      preLoaderRoute: typeof LayoutConfigurationsUsersRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/unites': {
      id: '/_layout/configurations/unites'
      path: '/unites'
      fullPath: '/configurations/unites'
      preLoaderRoute: typeof LayoutConfigurationsUnitesRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/types-prelevement': {
      id: '/_layout/configurations/types-prelevement'
      path: '/types-prelevement'
      fullPath: '/configurations/types-prelevement'
      preLoaderRoute: typeof LayoutConfigurationsTypesPrelevementRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/titres': {
      id: '/_layout/configurations/titres'
      path: '/titres'
      fullPath: '/configurations/titres'
      preLoaderRoute: typeof LayoutConfigurationsTitresRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/tarifs-assurance': {
      id: '/_layout/configurations/tarifs-assurance'
      path: '/tarifs-assurance'
      fullPath: '/configurations/tarifs-assurance'
      preLoaderRoute: typeof LayoutConfigurationsTarifsAssuranceRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/roles': {
      id: '/_layout/configurations/roles'
      path: '/roles'
      fullPath: '/configurations/roles'
      preLoaderRoute: typeof LayoutConfigurationsRolesRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/regles-validation': {
      id: '/_layout/configurations/regles-validation'
      path: '/regles-validation'
      fullPath: '/configurations/regles-validation'
      preLoaderRoute: typeof LayoutConfigurationsReglesValidationRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/regles-automatisees': {
      id: '/_layout/configurations/regles-automatisees'
      path: '/regles-automatisees'
      fullPath: '/configurations/regles-automatisees'
      preLoaderRoute: typeof LayoutConfigurationsReglesAutomatiseesRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/rapports': {
      id: '/_layout/configurations/rapports'
      path: '/rapports'
      fullPath: '/configurations/rapports'
      preLoaderRoute: typeof LayoutConfigurationsRapportsRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/permissions': {
      id: '/_layout/configurations/permissions'
      path: '/permissions'
      fullPath: '/configurations/permissions'
      preLoaderRoute: typeof LayoutConfigurationsPermissionsRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/motifs-rejet': {
      id: '/_layout/configurations/motifs-rejet'
      path: '/motifs-rejet'
      fullPath: '/configurations/motifs-rejet'
      preLoaderRoute: typeof LayoutConfigurationsMotifsRejetRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/methodes-paiement': {
      id: '/_layout/configurations/methodes-paiement'
      path: '/methodes-paiement'
      fullPath: '/configurations/methodes-paiement'
      preLoaderRoute: typeof LayoutConfigurationsMethodesPaiementRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/laboratoire': {
      id: '/_layout/configurations/laboratoire'
      path: '/laboratoire'
      fullPath: '/configurations/laboratoire'
      preLoaderRoute: typeof LayoutConfigurationsLaboratoireRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/finance': {
      id: '/_layout/configurations/finance'
      path: '/finance'
      fullPath: '/configurations/finance'
      preLoaderRoute: typeof LayoutConfigurationsFinanceRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/contexts-patient': {
      id: '/_layout/configurations/contexts-patient'
      path: '/contexts-patient'
      fullPath: '/configurations/contexts-patient'
      preLoaderRoute: typeof LayoutConfigurationsContextsPatientRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/categories': {
      id: '/_layout/configurations/categories'
      path: '/categories'
      fullPath: '/configurations/categories'
      preLoaderRoute: typeof LayoutConfigurationsCategoriesRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/catalogue': {
      id: '/_layout/configurations/catalogue'
      path: '/catalogue'
      fullPath: '/configurations/catalogue'
      preLoaderRoute: typeof LayoutConfigurationsCatalogueRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/audit': {
      id: '/_layout/configurations/audit'
      path: '/audit'
      fullPath: '/configurations/audit'
      preLoaderRoute: typeof LayoutConfigurationsAuditRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/assureurs': {
      id: '/_layout/configurations/assureurs'
      path: '/assureurs'
      fullPath: '/configurations/assureurs'
      preLoaderRoute: typeof LayoutConfigurationsAssureursRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/configurations/analytes': {
      id: '/_layout/configurations/analytes'
      path: '/analytes'
      fullPath: '/configurations/analytes'
      preLoaderRoute: typeof LayoutConfigurationsAnalytesRouteImport
      parentRoute: typeof LayoutConfigurationsRoute
    }
    '/_layout/commissions/entries': {
      id: '/_layout/commissions/entries'
      path: '/entries'
      fullPath: '/commissions/entries'
      preLoaderRoute: typeof LayoutCommissionsEntriesRouteImport
      parentRoute: typeof LayoutCommissionsRoute
    }
    '/_layout/orders/$orderId/': {
      id: '/_layout/orders/$orderId/'
      path: '/'
      fullPath: '/orders/$orderId/'
      preLoaderRoute: typeof LayoutOrdersOrderIdIndexRouteImport
      parentRoute: typeof LayoutOrdersOrderIdRoute
    }
    '/_layout/commissions/payments/': {
      id: '/_layout/commissions/payments/'
      path: '/payments'
      fullPath: '/commissions/payments/'
      preLoaderRoute: typeof LayoutCommissionsPaymentsIndexRouteImport
      parentRoute: typeof LayoutCommissionsRoute
    }
    '/_layout/orders/$orderId/report': {
      id: '/_layout/orders/$orderId/report'
      path: '/report'
      fullPath: '/orders/$orderId/report'
      preLoaderRoute: typeof LayoutOrdersOrderIdReportRouteImport
      parentRoute: typeof LayoutOrdersOrderIdRoute
    }
    '/_layout/orders/$orderId/edit': {
      id: '/_layout/orders/$orderId/edit'
      path: '/edit'
      fullPath: '/orders/$orderId/edit'
      preLoaderRoute: typeof LayoutOrdersOrderIdEditRouteImport
      parentRoute: typeof LayoutOrdersOrderIdRoute
    }
    '/_layout/commissions/payments/new': {
      id: '/_layout/commissions/payments/new'
      path: '/payments/new'
      fullPath: '/commissions/payments/new'
      preLoaderRoute: typeof LayoutCommissionsPaymentsNewRouteImport
      parentRoute: typeof LayoutCommissionsRoute
    }
    '/_layout/commissions/payments/$paymentId': {
      id: '/_layout/commissions/payments/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/commissions/payments/$paymentId'
      preLoaderRoute: typeof LayoutCommissionsPaymentsPaymentIdRouteImport
      parentRoute: typeof LayoutCommissionsRoute
    }
  }
}

interface LayoutCommissionsRouteChildren {
  LayoutCommissionsEntriesRoute: typeof LayoutCommissionsEntriesRoute
  LayoutCommissionsIndexRoute: typeof LayoutCommissionsIndexRoute
  LayoutCommissionsPaymentsPaymentIdRoute: typeof LayoutCommissionsPaymentsPaymentIdRoute
  LayoutCommissionsPaymentsNewRoute: typeof LayoutCommissionsPaymentsNewRoute
  LayoutCommissionsPaymentsIndexRoute: typeof LayoutCommissionsPaymentsIndexRoute
}

const LayoutCommissionsRouteChildren: LayoutCommissionsRouteChildren = {
  LayoutCommissionsEntriesRoute: LayoutCommissionsEntriesRoute,
  LayoutCommissionsIndexRoute: LayoutCommissionsIndexRoute,
  LayoutCommissionsPaymentsPaymentIdRoute:
    LayoutCommissionsPaymentsPaymentIdRoute,
  LayoutCommissionsPaymentsNewRoute: LayoutCommissionsPaymentsNewRoute,
  LayoutCommissionsPaymentsIndexRoute: LayoutCommissionsPaymentsIndexRoute,
}

const LayoutCommissionsRouteWithChildren =
  LayoutCommissionsRoute._addFileChildren(LayoutCommissionsRouteChildren)

interface LayoutConfigurationsRouteChildren {
  LayoutConfigurationsAnalytesRoute: typeof LayoutConfigurationsAnalytesRoute
  LayoutConfigurationsAssureursRoute: typeof LayoutConfigurationsAssureursRoute
  LayoutConfigurationsAuditRoute: typeof LayoutConfigurationsAuditRoute
  LayoutConfigurationsCatalogueRoute: typeof LayoutConfigurationsCatalogueRoute
  LayoutConfigurationsCategoriesRoute: typeof LayoutConfigurationsCategoriesRoute
  LayoutConfigurationsContextsPatientRoute: typeof LayoutConfigurationsContextsPatientRoute
  LayoutConfigurationsFinanceRoute: typeof LayoutConfigurationsFinanceRoute
  LayoutConfigurationsLaboratoireRoute: typeof LayoutConfigurationsLaboratoireRoute
  LayoutConfigurationsMethodesPaiementRoute: typeof LayoutConfigurationsMethodesPaiementRoute
  LayoutConfigurationsMotifsRejetRoute: typeof LayoutConfigurationsMotifsRejetRoute
  LayoutConfigurationsPermissionsRoute: typeof LayoutConfigurationsPermissionsRoute
  LayoutConfigurationsRapportsRoute: typeof LayoutConfigurationsRapportsRoute
  LayoutConfigurationsReglesAutomatiseesRoute: typeof LayoutConfigurationsReglesAutomatiseesRoute
  LayoutConfigurationsReglesValidationRoute: typeof LayoutConfigurationsReglesValidationRoute
  LayoutConfigurationsRolesRoute: typeof LayoutConfigurationsRolesRoute
  LayoutConfigurationsTarifsAssuranceRoute: typeof LayoutConfigurationsTarifsAssuranceRoute
  LayoutConfigurationsTitresRoute: typeof LayoutConfigurationsTitresRoute
  LayoutConfigurationsTypesPrelevementRoute: typeof LayoutConfigurationsTypesPrelevementRoute
  LayoutConfigurationsUnitesRoute: typeof LayoutConfigurationsUnitesRoute
  LayoutConfigurationsUsersRoute: typeof LayoutConfigurationsUsersRoute
  LayoutConfigurationsIndexRoute: typeof LayoutConfigurationsIndexRoute
}

const LayoutConfigurationsRouteChildren: LayoutConfigurationsRouteChildren = {
  LayoutConfigurationsAnalytesRoute: LayoutConfigurationsAnalytesRoute,
  LayoutConfigurationsAssureursRoute: LayoutConfigurationsAssureursRoute,
  LayoutConfigurationsAuditRoute: LayoutConfigurationsAuditRoute,
  LayoutConfigurationsCatalogueRoute: LayoutConfigurationsCatalogueRoute,
  LayoutConfigurationsCategoriesRoute: LayoutConfigurationsCategoriesRoute,
  LayoutConfigurationsContextsPatientRoute:
    LayoutConfigurationsContextsPatientRoute,
  LayoutConfigurationsFinanceRoute: LayoutConfigurationsFinanceRoute,
  LayoutConfigurationsLaboratoireRoute: LayoutConfigurationsLaboratoireRoute,
  LayoutConfigurationsMethodesPaiementRoute:
    LayoutConfigurationsMethodesPaiementRoute,
  LayoutConfigurationsMotifsRejetRoute: LayoutConfigurationsMotifsRejetRoute,
  LayoutConfigurationsPermissionsRoute: LayoutConfigurationsPermissionsRoute,
  LayoutConfigurationsRapportsRoute: LayoutConfigurationsRapportsRoute,
  LayoutConfigurationsReglesAutomatiseesRoute:
    LayoutConfigurationsReglesAutomatiseesRoute,
  LayoutConfigurationsReglesValidationRoute:
    LayoutConfigurationsReglesValidationRoute,
  LayoutConfigurationsRolesRoute: LayoutConfigurationsRolesRoute,
  LayoutConfigurationsTarifsAssuranceRoute:
    LayoutConfigurationsTarifsAssuranceRoute,
  LayoutConfigurationsTitresRoute: LayoutConfigurationsTitresRoute,
  LayoutConfigurationsTypesPrelevementRoute:
    LayoutConfigurationsTypesPrelevementRoute,
  LayoutConfigurationsUnitesRoute: LayoutConfigurationsUnitesRoute,
  LayoutConfigurationsUsersRoute: LayoutConfigurationsUsersRoute,
  LayoutConfigurationsIndexRoute: LayoutConfigurationsIndexRoute,
}

const LayoutConfigurationsRouteWithChildren =
  LayoutConfigurationsRoute._addFileChildren(LayoutConfigurationsRouteChildren)

interface LayoutDoctorCommissionPaymentsRouteChildren {
  LayoutDoctorCommissionPaymentsPaymentIdRoute: typeof LayoutDoctorCommissionPaymentsPaymentIdRoute
  LayoutDoctorCommissionPaymentsNewRoute: typeof LayoutDoctorCommissionPaymentsNewRoute
  LayoutDoctorCommissionPaymentsIndexRoute: typeof LayoutDoctorCommissionPaymentsIndexRoute
}

const LayoutDoctorCommissionPaymentsRouteChildren: LayoutDoctorCommissionPaymentsRouteChildren =
  {
    LayoutDoctorCommissionPaymentsPaymentIdRoute:
      LayoutDoctorCommissionPaymentsPaymentIdRoute,
    LayoutDoctorCommissionPaymentsNewRoute:
      LayoutDoctorCommissionPaymentsNewRoute,
    LayoutDoctorCommissionPaymentsIndexRoute:
      LayoutDoctorCommissionPaymentsIndexRoute,
  }

const LayoutDoctorCommissionPaymentsRouteWithChildren =
  LayoutDoctorCommissionPaymentsRoute._addFileChildren(
    LayoutDoctorCommissionPaymentsRouteChildren,
  )

interface LayoutDoctorsRouteChildren {
  LayoutDoctorsDoctorIdRoute: typeof LayoutDoctorsDoctorIdRoute
  LayoutDoctorsIndexRoute: typeof LayoutDoctorsIndexRoute
}

const LayoutDoctorsRouteChildren: LayoutDoctorsRouteChildren = {
  LayoutDoctorsDoctorIdRoute: LayoutDoctorsDoctorIdRoute,
  LayoutDoctorsIndexRoute: LayoutDoctorsIndexRoute,
}

const LayoutDoctorsRouteWithChildren = LayoutDoctorsRoute._addFileChildren(
  LayoutDoctorsRouteChildren,
)

interface LayoutInvoicesRouteChildren {
  LayoutInvoicesInvoiceIdRoute: typeof LayoutInvoicesInvoiceIdRoute
  LayoutInvoicesIndexRoute: typeof LayoutInvoicesIndexRoute
}

const LayoutInvoicesRouteChildren: LayoutInvoicesRouteChildren = {
  LayoutInvoicesInvoiceIdRoute: LayoutInvoicesInvoiceIdRoute,
  LayoutInvoicesIndexRoute: LayoutInvoicesIndexRoute,
}

const LayoutInvoicesRouteWithChildren = LayoutInvoicesRoute._addFileChildren(
  LayoutInvoicesRouteChildren,
)

interface LayoutOrdersOrderIdRouteChildren {
  LayoutOrdersOrderIdEditRoute: typeof LayoutOrdersOrderIdEditRoute
  LayoutOrdersOrderIdReportRoute: typeof LayoutOrdersOrderIdReportRoute
  LayoutOrdersOrderIdIndexRoute: typeof LayoutOrdersOrderIdIndexRoute
}

const LayoutOrdersOrderIdRouteChildren: LayoutOrdersOrderIdRouteChildren = {
  LayoutOrdersOrderIdEditRoute: LayoutOrdersOrderIdEditRoute,
  LayoutOrdersOrderIdReportRoute: LayoutOrdersOrderIdReportRoute,
  LayoutOrdersOrderIdIndexRoute: LayoutOrdersOrderIdIndexRoute,
}

const LayoutOrdersOrderIdRouteWithChildren =
  LayoutOrdersOrderIdRoute._addFileChildren(LayoutOrdersOrderIdRouteChildren)

interface LayoutOrdersRouteChildren {
  LayoutOrdersOrderIdRoute: typeof LayoutOrdersOrderIdRouteWithChildren
  LayoutOrdersNewRoute: typeof LayoutOrdersNewRoute
  LayoutOrdersIndexRoute: typeof LayoutOrdersIndexRoute
}

const LayoutOrdersRouteChildren: LayoutOrdersRouteChildren = {
  LayoutOrdersOrderIdRoute: LayoutOrdersOrderIdRouteWithChildren,
  LayoutOrdersNewRoute: LayoutOrdersNewRoute,
  LayoutOrdersIndexRoute: LayoutOrdersIndexRoute,
}

const LayoutOrdersRouteWithChildren = LayoutOrdersRoute._addFileChildren(
  LayoutOrdersRouteChildren,
)

interface LayoutPatientsRouteChildren {
  LayoutPatientsPatientIdRoute: typeof LayoutPatientsPatientIdRoute
  LayoutPatientsIndexRoute: typeof LayoutPatientsIndexRoute
}

const LayoutPatientsRouteChildren: LayoutPatientsRouteChildren = {
  LayoutPatientsPatientIdRoute: LayoutPatientsPatientIdRoute,
  LayoutPatientsIndexRoute: LayoutPatientsIndexRoute,
}

const LayoutPatientsRouteWithChildren = LayoutPatientsRoute._addFileChildren(
  LayoutPatientsRouteChildren,
)

interface LayoutResultsRouteChildren {
  LayoutResultsOrderIdRoute: typeof LayoutResultsOrderIdRoute
  LayoutResultsIndexRoute: typeof LayoutResultsIndexRoute
}

const LayoutResultsRouteChildren: LayoutResultsRouteChildren = {
  LayoutResultsOrderIdRoute: LayoutResultsOrderIdRoute,
  LayoutResultsIndexRoute: LayoutResultsIndexRoute,
}

const LayoutResultsRouteWithChildren = LayoutResultsRoute._addFileChildren(
  LayoutResultsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCommissionsRoute: typeof LayoutCommissionsRouteWithChildren
  LayoutConfigurationsRoute: typeof LayoutConfigurationsRouteWithChildren
  LayoutDoctorCommissionPaymentsRoute: typeof LayoutDoctorCommissionPaymentsRouteWithChildren
  LayoutDoctorsRoute: typeof LayoutDoctorsRouteWithChildren
  LayoutInvoicesRoute: typeof LayoutInvoicesRouteWithChildren
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutOrdersRoute: typeof LayoutOrdersRouteWithChildren
  LayoutPatientsRoute: typeof LayoutPatientsRouteWithChildren
  LayoutResultsRoute: typeof LayoutResultsRouteWithChildren
  LayoutSpecimensRoute: typeof LayoutSpecimensRoute
  LayoutUserAccountRoute: typeof LayoutUserAccountRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCommissionsRoute: LayoutCommissionsRouteWithChildren,
  LayoutConfigurationsRoute: LayoutConfigurationsRouteWithChildren,
  LayoutDoctorCommissionPaymentsRoute:
    LayoutDoctorCommissionPaymentsRouteWithChildren,
  LayoutDoctorsRoute: LayoutDoctorsRouteWithChildren,
  LayoutInvoicesRoute: LayoutInvoicesRouteWithChildren,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutOrdersRoute: LayoutOrdersRouteWithChildren,
  LayoutPatientsRoute: LayoutPatientsRouteWithChildren,
  LayoutResultsRoute: LayoutResultsRouteWithChildren,
  LayoutSpecimensRoute: LayoutSpecimensRoute,
  LayoutUserAccountRoute: LayoutUserAccountRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
