-- =============================================================================
-- LIS — Laboratory Information System
-- PostgreSQL Schema
-- =============================================================================
-- Convention:
--   • All PKs are UUID generated by gen_random_uuid()
--   • All timestamps are TIMESTAMPTZ (UTC)
--   • Soft deletes via is_deleted BOOLEAN NOT NULL DEFAULT FALSE
--   • Snake_case naming throughout
-- =============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";      -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "btree_gist";    -- exclusion constraints on tsrange
CREATE EXTENSION IF NOT EXISTS "pg_trgm";       -- trigram indexes for patient search


-- =============================================================================
-- SECTION 1 — ENUMS
-- =============================================================================

CREATE TYPE gender_type          AS ENUM ('male', 'female');
CREATE TYPE data_type            AS ENUM ('numeric', 'text', 'options', 'image');
CREATE TYPE catalog_type         AS ENUM ('item', 'panel');
CREATE TYPE target_gender_type   AS ENUM ('male', 'female', 'all');
CREATE TYPE trigger_operator     AS ENUM ('gt', 'lt', 'eq', 'gte', 'lte', 'in');
CREATE TYPE rule_severity        AS ENUM ('warning', 'error');
CREATE TYPE order_status         AS ENUM ('registered', 'collected', 'in_progress', 'partial_results', 'completed', 'cancelled');
CREATE TYPE specimen_status      AS ENUM ('collected', 'rejected', 'processed');
CREATE TYPE result_status        AS ENUM ('pending', 'resulted', 'verified', 'rejected');
CREATE TYPE payout_status        AS ENUM ('pending', 'paid');
CREATE TYPE payment_status       AS ENUM ('unpaid', 'paid', 'partial', 'refunded');
CREATE TYPE report_channel       AS ENUM ('print', 'email', 'whatsapp', 'portal');
CREATE TYPE delivery_status      AS ENUM ('pending', 'sent', 'failed');
CREATE TYPE notification_type    AS ENUM ('result_ready', 'order_update', 'report_released', 'general');
CREATE TYPE notification_channel AS ENUM ('sms', 'email', 'whatsapp', 'in_app');
CREATE TYPE notification_status  AS ENUM ('pending', 'sent', 'failed');
CREATE TYPE critical_method      AS ENUM ('call', 'sms', 'in_app', 'email');
CREATE TYPE audit_action         AS ENUM ('insert', 'update', 'delete');


-- =============================================================================
-- SECTION 2 — LOOKUP / REFERENCE TABLES
-- =============================================================================

CREATE TABLE titles (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(100) NOT NULL,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE units (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(100) NOT NULL,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Examples: fasting, pregnant, pediatric, post-dialysis
CREATE TABLE patient_contexts (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(100) NOT NULL,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE payment_methods (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(100) NOT NULL,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE rejection_reasons (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(255) NOT NULL,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =============================================================================
-- SECTION 3 — USERS & AUTH
-- =============================================================================

CREATE TABLE users (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash TEXT        NOT NULL,
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX idx_users_email ON users (email);


-- =============================================================================
-- SECTION 4 — RBAC
-- =============================================================================

CREATE TABLE permissions (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    resource    VARCHAR(100) NOT NULL,
    action      VARCHAR(100) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_permissions_resource_action UNIQUE (resource, action)
);

CREATE TABLE roles (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    is_default  BOOLEAN     NOT NULL DEFAULT FALSE,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE role_permissions (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    role_id       UUID        NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission_id UUID        NOT NULL REFERENCES permissions (id) ON DELETE CASCADE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_role_permissions UNIQUE (role_id, permission_id)
);

CREATE TABLE user_roles (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id       UUID        NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    assigned_by_id UUID       NOT NULL REFERENCES users (id),
    assigned_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at    TIMESTAMPTZ,             -- NULL = permanent
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Prevent duplicate active role assignments per user
CREATE UNIQUE INDEX uq_active_user_role
    ON user_roles (user_id, role_id)
    WHERE expires_at IS NULL;

CREATE INDEX idx_user_roles_user_id ON user_roles (user_id);
CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);


-- =============================================================================
-- SECTION 5 — INSURANCE PROVIDERS
-- (declared before patients to satisfy FK ordering)
-- =============================================================================

CREATE TABLE insurance_providers (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(255) NOT NULL,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =============================================================================
-- SECTION 6 — PATIENTS
-- =============================================================================

CREATE TABLE patients (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    identifier  VARCHAR(100) NOT NULL,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    date_of_birth DATE       NOT NULL,
    gender      gender_type  NOT NULL,
    phone       VARCHAR(50),
    address     TEXT,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_patients_identifier UNIQUE (identifier)
);

-- Trigram indexes for fuzzy patient search
CREATE INDEX idx_patients_identifier  ON patients (identifier);
CREATE INDEX idx_patients_first_name  ON patients USING GIN (first_name gin_trgm_ops);
CREATE INDEX idx_patients_last_name   ON patients USING GIN (last_name gin_trgm_ops);

CREATE TABLE patient_insurance (
    id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id           UUID        NOT NULL REFERENCES patients (id),
    insurance_provider_id UUID       NOT NULL REFERENCES insurance_providers (id),
    policy_number        VARCHAR(100) NOT NULL,
    is_primary           BOOLEAN     NOT NULL DEFAULT FALSE,
    is_deleted           BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Only one active primary insurance per patient
CREATE UNIQUE INDEX uq_primary_insurance_per_patient
    ON patient_insurance (patient_id)
    WHERE is_primary = TRUE AND is_deleted = FALSE;

CREATE INDEX idx_patient_insurance_patient_id ON patient_insurance (patient_id);


-- =============================================================================
-- SECTION 7 — DOCTORS
-- =============================================================================

CREATE TABLE doctors (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    provenance  VARCHAR(255),
    phone       VARCHAR(50),
    title_id    UUID        REFERENCES titles (id),
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_doctors_title_id ON doctors (title_id);


-- =============================================================================
-- SECTION 8 — SPECIMEN TYPES
-- =============================================================================

CREATE TABLE specimen_types (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    color       VARCHAR(50),             -- hex or CSS color for tube display
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =============================================================================
-- SECTION 9 — CATALOG
-- =============================================================================

CREATE TABLE categories (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(100) NOT NULL,
    sort_order  INTEGER     NOT NULL DEFAULT 0,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE catalog (
    id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    type         catalog_type NOT NULL,
    name         VARCHAR(255) NOT NULL,
    code         VARCHAR(50)  NOT NULL,
    price        NUMERIC(12, 2) NOT NULL DEFAULT 0,
    is_orderable BOOLEAN      NOT NULL DEFAULT TRUE,
    category_id  UUID         REFERENCES categories (id),
    is_deleted   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_catalog_code UNIQUE (code)
);

CREATE INDEX idx_catalog_category_id ON catalog (category_id);
CREATE INDEX idx_catalog_type        ON catalog (type);
CREATE INDEX idx_catalog_code        ON catalog (code);

CREATE TABLE catalog_specimen_requirements (
    catalog_id       UUID          NOT NULL REFERENCES catalog (id) ON DELETE CASCADE,
    specimen_type_id UUID          NOT NULL REFERENCES specimen_types (id),
    volume_ml        NUMERIC(6, 2),
    instructions     TEXT,

    PRIMARY KEY (catalog_id, specimen_type_id)
);

CREATE TABLE catalog_panel_items (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    panel_id   UUID        NOT NULL REFERENCES catalog (id) ON DELETE CASCADE,
    test_id    UUID        NOT NULL REFERENCES catalog (id) ON DELETE CASCADE,
    sort_order INTEGER     NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_panel_test UNIQUE (panel_id, test_id),
    -- Panel cannot reference itself
    CONSTRAINT chk_panel_not_self CHECK (panel_id <> test_id)
);

-- Enforce panel_id must be type='panel' and test_id must be type='item'
-- via triggers (check constraints cannot reference other rows in PostgreSQL)
CREATE OR REPLACE FUNCTION check_catalog_panel_items()
RETURNS TRIGGER AS $$
BEGIN
    IF (SELECT type FROM catalog WHERE id = NEW.panel_id) <> 'panel' THEN
        RAISE EXCEPTION 'panel_id must reference a catalog entry of type ''panel''';
    END IF;
    IF (SELECT type FROM catalog WHERE id = NEW.test_id) <> 'item' THEN
        RAISE EXCEPTION 'test_id must reference a catalog entry of type ''item''';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_catalog_panel_items
    BEFORE INSERT OR UPDATE ON catalog_panel_items
    FOR EACH ROW EXECUTE FUNCTION check_catalog_panel_items();


-- =============================================================================
-- SECTION 10 — ANALYTES
-- =============================================================================

CREATE TABLE analytes (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    code                VARCHAR(50) NOT NULL,
    name                VARCHAR(255) NOT NULL,
    unit_id             UUID        REFERENCES units (id),
    data_type           data_type    NOT NULL,
    options_data        JSONB,       -- for type='options': array of allowed values
    reference_text      TEXT,        -- free-text reference range description
    is_calculated       BOOLEAN     NOT NULL DEFAULT FALSE,
    calculation_formula TEXT,        -- e.g. "{A001} - {A002} / 5"
    is_deleted          BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_analytes_code UNIQUE (code)
);

CREATE INDEX idx_analytes_code    ON analytes (code);
CREATE INDEX idx_analytes_unit_id ON analytes (unit_id);

CREATE TABLE catalog_item_analytes (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    catalog_item_id UUID        NOT NULL REFERENCES catalog (id) ON DELETE CASCADE,
    analyte_id      UUID        NOT NULL REFERENCES analytes (id),
    sort_order      INTEGER     NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_catalog_item_analyte UNIQUE (catalog_item_id, analyte_id)
);

CREATE INDEX idx_catalog_item_analytes_catalog  ON catalog_item_analytes (catalog_item_id);
CREATE INDEX idx_catalog_item_analytes_analyte  ON catalog_item_analytes (analyte_id);


-- =============================================================================
-- SECTION 11 — VALIDATION & RULES
-- =============================================================================

CREATE TABLE validation_rules (
    id                  UUID               PRIMARY KEY DEFAULT gen_random_uuid(),
    analyte_id          UUID               NOT NULL REFERENCES analytes (id),
    target_gender       target_gender_type NOT NULL DEFAULT 'all',
    min_age_years       INTEGER,           -- nullable = no lower bound
    max_age_years       INTEGER,           -- nullable = no upper bound
    required_context_id UUID               REFERENCES patient_contexts (id),  -- nullable = all contexts
    priority            INTEGER            NOT NULL DEFAULT 0,  -- higher = more specific
    absurd_min          NUMERIC(12, 4),
    absurd_max          NUMERIC(12, 4),
    panic_min           NUMERIC(12, 4),
    panic_max           NUMERIC(12, 4),
    normal_min          NUMERIC(12, 4),
    normal_max          NUMERIC(12, 4),
    expected_value      NUMERIC(12, 4),
    max_delta_percent   NUMERIC(6, 2),
    created_at          TIMESTAMPTZ        NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ        NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_validation_rules_analyte_id ON validation_rules (analyte_id);
CREATE INDEX idx_validation_rules_priority   ON validation_rules (analyte_id, priority DESC);

CREATE TABLE consistency_rules (
    id                  UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    name                VARCHAR(255)  NOT NULL,
    formula             TEXT          NOT NULL,  -- e.g. "{A001} / {A002} > 0.85"
    formula_description TEXT,                    -- plain English explanation
    error_message       TEXT          NOT NULL,
    severity            rule_severity NOT NULL,
    is_deleted          BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TABLE consistency_rule_analytes (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    rule_id    UUID        NOT NULL REFERENCES consistency_rules (id) ON DELETE CASCADE,
    analyte_id UUID        NOT NULL REFERENCES analytes (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_consistency_rule_analyte UNIQUE (rule_id, analyte_id)
);

CREATE INDEX idx_consistency_rule_analytes_rule    ON consistency_rule_analytes (rule_id);
CREATE INDEX idx_consistency_rule_analytes_analyte ON consistency_rule_analytes (analyte_id);

CREATE TABLE reflex_rules (
    id                 UUID             PRIMARY KEY DEFAULT gen_random_uuid(),
    trigger_analyte_id UUID             NOT NULL REFERENCES analytes (id),
    trigger_operator   trigger_operator NOT NULL,
    trigger_value      VARCHAR(255)     NOT NULL,
    action_catalog_id  UUID             NOT NULL REFERENCES catalog (id),
    is_deleted         BOOLEAN          NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ      NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_reflex_rules_trigger_analyte ON reflex_rules (trigger_analyte_id);


-- =============================================================================
-- SECTION 12 — INSTRUMENTS
-- =============================================================================

CREATE TABLE instruments (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name          VARCHAR(255) NOT NULL,
    model         VARCHAR(255),
    serial_number VARCHAR(100),
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =============================================================================
-- SECTION 13 — ORDERS
-- (OrderSpecimens declared before OrderItems due to FK dependency)
-- =============================================================================

CREATE TABLE orders (
    id                  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id          UUID         NOT NULL REFERENCES patients (id),
    doctor_id           UUID         NOT NULL REFERENCES doctors (id),
    patient_insurance_id UUID        REFERENCES patient_insurance (id),  -- nullable = cash
    status              order_status NOT NULL DEFAULT 'registered',
    patient_context_id  UUID         REFERENCES patient_contexts (id),
    notes               TEXT,
    created_by          UUID         NOT NULL REFERENCES users (id),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_orders_patient_id  ON orders (patient_id);
CREATE INDEX idx_orders_doctor_id   ON orders (doctor_id);
CREATE INDEX idx_orders_status      ON orders (status);
CREATE INDEX idx_orders_created_at  ON orders (created_at DESC);

CREATE TABLE order_specimens (
    id                 UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id           UUID            NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    specimen_type_id   UUID            NOT NULL REFERENCES specimen_types (id),
    collection_time    TIMESTAMPTZ,
    collected_by       UUID            REFERENCES users (id),
    status             specimen_status NOT NULL DEFAULT 'collected',
    rejection_reason_id UUID           REFERENCES rejection_reasons (id),
    notes              TEXT,
    created_at         TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_order_specimens_order_id ON order_specimens (order_id);
CREATE INDEX idx_order_specimens_status   ON order_specimens (status);

CREATE TABLE order_items (
    id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id             UUID        NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    catalog_id           UUID        NOT NULL REFERENCES catalog (id),
    order_specimen_id    UUID        REFERENCES order_specimens (id),  -- linked after specimen determination
    catalog_price        NUMERIC(12, 2) NOT NULL,
    price_charged        NUMERIC(12, 2) NOT NULL,
    price_override_reason TEXT,
    is_covered_by_insurance BOOLEAN  NOT NULL DEFAULT FALSE,
    sort_order           INTEGER     NOT NULL DEFAULT 0,
    is_reflex_added      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_order_items_order_id         ON order_items (order_id);
CREATE INDEX idx_order_items_catalog_id       ON order_items (catalog_id);
CREATE INDEX idx_order_items_order_specimen_id ON order_items (order_specimen_id);

CREATE TABLE order_catalog_item_analytes (
    id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    order_item_id          UUID        NOT NULL REFERENCES order_items (id) ON DELETE CASCADE,
    catalog_item_analyte_id UUID       NOT NULL REFERENCES catalog_item_analytes (id),
    sort_order             INTEGER     NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_order_catalog_item_analyte UNIQUE (order_item_id, catalog_item_analyte_id)
);

CREATE INDEX idx_order_catalog_item_analytes_order_item ON order_catalog_item_analytes (order_item_id);


-- =============================================================================
-- SECTION 14 — RESULTS
-- =============================================================================

CREATE TABLE analyte_results (
    id                 UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    order_item_id      UUID          NOT NULL REFERENCES order_items (id) ON DELETE CASCADE,
    analyte_id         UUID          NOT NULL REFERENCES analytes (id),
    specimen_id        UUID          NOT NULL REFERENCES order_specimens (id),
    instrument_id      UUID          REFERENCES instruments (id),   -- nullable = manual entry
    result_value       TEXT,                                         -- stored as text, validated by data_type
    validation_rule_id UUID          REFERENCES validation_rules (id),
    is_abnormal        BOOLEAN       NOT NULL DEFAULT FALSE,
    is_critical        BOOLEAN       NOT NULL DEFAULT FALSE,
    delta_flag         BOOLEAN       NOT NULL DEFAULT FALSE,
    is_rejected        BOOLEAN       NOT NULL DEFAULT FALSE,
    rejection_reason   TEXT,
    status             result_status NOT NULL DEFAULT 'pending',
    resulted_by_id     UUID          REFERENCES users (id),
    resulted_at        TIMESTAMPTZ,
    verified_by_id     UUID          REFERENCES users (id),
    verified_at        TIMESTAMPTZ,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_analyte_results_order_item_id ON analyte_results (order_item_id);
CREATE INDEX idx_analyte_results_analyte_id    ON analyte_results (analyte_id);
CREATE INDEX idx_analyte_results_specimen_id   ON analyte_results (specimen_id);
CREATE INDEX idx_analyte_results_status        ON analyte_results (status);
CREATE INDEX idx_analyte_results_is_critical   ON analyte_results (is_critical) WHERE is_critical = TRUE;

CREATE TABLE analyte_result_comments (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    analyte_result_id UUID       NOT NULL REFERENCES analyte_results (id) ON DELETE CASCADE,
    user_id          UUID        NOT NULL REFERENCES users (id),
    comment          TEXT        NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_analyte_result_comments_result_id ON analyte_result_comments (analyte_result_id);

CREATE TABLE critical_notifications (
    id                UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    analyte_result_id UUID            NOT NULL REFERENCES analyte_results (id),
    notified_by_id    UUID            NOT NULL REFERENCES users (id),
    notified_to_id    UUID            NOT NULL REFERENCES users (id),
    notified_at       TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    method            critical_method NOT NULL,
    acknowledged      BOOLEAN         NOT NULL DEFAULT FALSE,
    acknowledged_at   TIMESTAMPTZ,
    notes             TEXT,
    created_at        TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_critical_notifications_result_id     ON critical_notifications (analyte_result_id);
CREATE INDEX idx_critical_notifications_acknowledged  ON critical_notifications (acknowledged) WHERE acknowledged = FALSE;


-- =============================================================================
-- SECTION 15 — REPORTS
-- =============================================================================

CREATE TABLE report_templates (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name                VARCHAR(255) NOT NULL,
    description         TEXT,
    template_storage_url TEXT,
    is_default          BOOLEAN     NOT NULL DEFAULT FALSE,
    is_deleted          BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Only one active default template
CREATE UNIQUE INDEX uq_default_report_template
    ON report_templates (is_default)
    WHERE is_default = TRUE AND is_deleted = FALSE;

CREATE TABLE reports (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id            UUID            NOT NULL REFERENCES orders (id),
    version             INTEGER         NOT NULL DEFAULT 1,
    report_template_id  UUID            REFERENCES report_templates (id),
    released_by_id      UUID            NOT NULL REFERENCES users (id),
    released_at         TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    channel             report_channel  NOT NULL,
    delivery_status     delivery_status NOT NULL DEFAULT 'pending',
    recipient_note      TEXT,
    report_storage_url  TEXT,
    is_voided           BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_reports_order_id ON reports (order_id);
CREATE INDEX idx_reports_is_voided ON reports (is_voided) WHERE is_voided = FALSE;


-- =============================================================================
-- SECTION 16 — NOTIFICATIONS
-- =============================================================================

CREATE TABLE notifications (
    id         UUID                 PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id   UUID                 REFERENCES orders (id),       -- nullable
    patient_id UUID                 REFERENCES patients (id),     -- nullable
    user_id    UUID                 NOT NULL REFERENCES users (id),
    type       notification_type    NOT NULL,
    channel    notification_channel NOT NULL,
    message    TEXT                 NOT NULL,
    status     notification_status  NOT NULL DEFAULT 'pending',
    sent_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ          NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ          NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notifications_user_id   ON notifications (user_id);
CREATE INDEX idx_notifications_order_id  ON notifications (order_id);
CREATE INDEX idx_notifications_status    ON notifications (status);


-- =============================================================================
-- SECTION 17 — INSURANCE PRICING
-- =============================================================================

CREATE TABLE insurance_pricing (
    id                    UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    insurance_provider_id UUID          NOT NULL REFERENCES insurance_providers (id),
    catalog_id            UUID          NOT NULL REFERENCES catalog (id),
    insurance_price       NUMERIC(12, 2) NOT NULL,
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_insurance_pricing UNIQUE (insurance_provider_id, catalog_id)
);

CREATE INDEX idx_insurance_pricing_provider ON insurance_pricing (insurance_provider_id);
CREATE INDEX idx_insurance_pricing_catalog  ON insurance_pricing (catalog_id);


-- =============================================================================
-- SECTION 18 — INVOICES
-- =============================================================================

CREATE TABLE invoices (
    id              UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id        UUID           NOT NULL REFERENCES orders (id),
    version         INTEGER        NOT NULL DEFAULT 1,
    is_voided       BOOLEAN        NOT NULL DEFAULT FALSE,
    total_amount    NUMERIC(12, 2) NOT NULL,
    discount        NUMERIC(12, 2) NOT NULL DEFAULT 0,
    net_amount      NUMERIC(12, 2) NOT NULL,
    amount_paid     NUMERIC(12, 2) NOT NULL DEFAULT 0,
    payment_status  payment_status NOT NULL DEFAULT 'unpaid',
    payment_method_id UUID         REFERENCES payment_methods (id),
    created_by_id   UUID           NOT NULL REFERENCES users (id),
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_invoices_order_id       ON invoices (order_id);
CREATE INDEX idx_invoices_payment_status ON invoices (payment_status);
CREATE INDEX idx_invoices_is_voided      ON invoices (is_voided) WHERE is_voided = FALSE;


-- =============================================================================
-- SECTION 19 — DOCTOR COMMISSIONS
-- =============================================================================

CREATE TABLE doctor_commission_configs (
    id                       UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    doctor_id                UUID          NOT NULL REFERENCES doctors (id),
    commission_rate          NUMERIC(5, 4) NOT NULL,          -- e.g. 0.1500 = 15%
    insurance_commission_rate NUMERIC(5, 4) NOT NULL,
    effective_from           DATE          NOT NULL,
    effective_until          DATE,                             -- nullable = open-ended
    created_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- Prevent overlapping date ranges per doctor using exclusion constraint
ALTER TABLE doctor_commission_configs
    ADD CONSTRAINT no_overlapping_commission_configs
    EXCLUDE USING GIST (
        doctor_id WITH =,
        daterange(effective_from, effective_until, '[)') WITH &&
    );

CREATE INDEX idx_commission_configs_doctor_id ON doctor_commission_configs (doctor_id);

CREATE TABLE doctor_commission_entries (
    id                UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id          UUID          NOT NULL REFERENCES orders (id),
    doctor_id         UUID          NOT NULL REFERENCES doctors (id),
    order_net_amount  NUMERIC(12, 2) NOT NULL,
    rate_applied      NUMERIC(5, 4)  NOT NULL,
    commission_amount NUMERIC(12, 2) NOT NULL,
    payout_status     payout_status  NOT NULL DEFAULT 'pending',
    paid_at           TIMESTAMPTZ,
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ    NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_commission_entry_per_order UNIQUE (order_id, doctor_id)
);

CREATE INDEX idx_commission_entries_doctor_id     ON doctor_commission_entries (doctor_id);
CREATE INDEX idx_commission_entries_payout_status ON doctor_commission_entries (payout_status);

CREATE TABLE doctor_commission_payments (
    id                     UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    doctor_id              UUID          NOT NULL REFERENCES doctors (id),
    total_commission_amount NUMERIC(12, 2) NOT NULL,
    created_by             UUID          NOT NULL REFERENCES users (id),
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_commission_payments_doctor_id ON doctor_commission_payments (doctor_id);

CREATE TABLE doctor_commission_payment_entries (
    id                         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    commission_payment_id      UUID        NOT NULL REFERENCES doctor_commission_payments (id) ON DELETE CASCADE,
    commission_entry_id        UUID        NOT NULL REFERENCES doctor_commission_entries (id),
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_payment_entry UNIQUE (commission_payment_id, commission_entry_id)
);

CREATE INDEX idx_commission_payment_entries_payment_id ON doctor_commission_payment_entries (commission_payment_id);
CREATE INDEX idx_commission_payment_entries_entry_id   ON doctor_commission_payment_entries (commission_entry_id);


-- =============================================================================
-- SECTION 20 — AUDIT LOGS
-- =============================================================================

CREATE TABLE audit_logs (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    table_name      VARCHAR(100) NOT NULL,
    record_id       UUID         NOT NULL,
    action          audit_action NOT NULL,
    old_values      JSONB,
    new_values      JSONB,
    performed_by_id UUID         REFERENCES users (id),
    performed_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_logs_table_name     ON audit_logs (table_name);
CREATE INDEX idx_audit_logs_record_id      ON audit_logs (record_id);
CREATE INDEX idx_audit_logs_performed_by   ON audit_logs (performed_by_id);
CREATE INDEX idx_audit_logs_performed_at   ON audit_logs (performed_at DESC);


-- =============================================================================
-- SECTION 21 — UPDATED_AT TRIGGER
-- (Applied to all tables with updated_at column)
-- =============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to every table that has updated_at
DO $$
DECLARE
    t TEXT;
BEGIN
    FOR t IN
        SELECT table_name
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND column_name  = 'updated_at'
    LOOP
        EXECUTE format(
            'CREATE TRIGGER trg_set_updated_at
             BEFORE UPDATE ON %I
             FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
            t
        );
    END LOOP;
END;
$$;


-- =============================================================================
-- SECTION 22 — SEED DATA
-- =============================================================================

-- Seed: Default roles
INSERT INTO roles (id, name, description, is_default) VALUES
    (gen_random_uuid(), 'super_admin',  'Full system access',                               FALSE),
    (gen_random_uuid(), 'lab_manager',  'Operations, catalog, staff management',             FALSE),
    (gen_random_uuid(), 'receptionist', 'Patient registration, orders, payments',            TRUE),
    (gen_random_uuid(), 'phlebotomist', 'Specimen collection',                               FALSE),
    (gen_random_uuid(), 'supervisor',   'Oversight and critical notification acknowledgement', FALSE),
    (gen_random_uuid(), 'technician',   'Result entry',                                      FALSE),
    (gen_random_uuid(), 'pathologist',  'Result verification and report release',             FALSE),
    (gen_random_uuid(), 'finance',      'Invoices, payments, commissions',                   FALSE),
    (gen_random_uuid(), 'doctor',       'View own patients results and reports',              FALSE),
    (gen_random_uuid(), 'patient',      'View own reports via portal',                       FALSE);

-- Seed: All permissions
INSERT INTO permissions (resource, action, description) VALUES
    -- Patients
    ('patients',            'create',      'Register a new patient'),
    ('patients',            'view',        'Search and view patient records'),
    ('patients',            'edit',        'Update patient demographics'),
    -- Patient Insurance
    ('patient_insurance',   'create',      'Add insurance policy to patient'),
    ('patient_insurance',   'view',        'View patient insurance policies'),
    ('patient_insurance',   'edit',        'Edit insurance policy details'),
    -- Orders
    ('orders',              'create',      'Create a new order'),
    ('orders',              'view',        'View order details and status'),
    ('orders',              'edit',        'Edit order before specimen collection'),
    ('orders',              'cancel',      'Cancel an order'),
    -- Order Items
    ('order_items',         'create',      'Add tests to an order'),
    ('order_items',         'view',        'View order item details'),
    ('order_items',         'edit',        'Adjust price override or sort order'),
    ('order_items',         'delete',      'Remove a test before processing'),
    -- Specimens
    ('specimens',           'view',        'View specimen details'),
    ('specimens',           'collect',     'Record specimen collection'),
    ('specimens',           'reject',      'Mark specimen as rejected'),
    -- Results
    ('results',             'enter',       'Enter result values'),
    ('results',             'edit',        'Correct a result before verification'),
    ('results',             'verify',      'Verify results as pathologist'),
    ('results',             'view',        'View result values and flags'),
    -- Critical Notifications
    ('critical_notifications', 'view',      'View critical notifications'),
    ('critical_notifications', 'acknowledge','Acknowledge a critical notification'),
    -- Reports
    ('reports',             'release',     'Release a report'),
    ('reports',             'void',        'Void a superseded report version'),
    ('reports',             'view',        'View released reports'),
    -- Invoices
    ('invoices',            'create',      'Create an invoice'),
    ('invoices',            'view',        'View invoice details'),
    ('invoices',            'edit',        'Adjust discount or amounts'),
    ('invoices',            'void',        'Void and reissue an invoice'),
    -- Payments
    ('payments',            'view',        'View payment records'),
    ('payments',            'collect',     'Record a payment'),
    ('payments',            'refund',      'Issue a refund'),
    -- Commissions
    ('commissions',         'view',        'View commission entries'),
    ('commissions',         'pay',         'Record a commission payout'),
    -- Catalog & Rules
    ('catalog',             'manage',      'Full CRUD on catalog items and panels'),
    ('rules',               'manage',      'Full CRUD on validation, consistency, reflex rules'),
    -- Users & Roles
    ('users',               'manage',      'Create, edit, deactivate users'),
    ('roles',               'manage',      'Create roles and assign permissions'),
    -- Audit
    ('audit',               'view',        'Read-only access to audit logs');


-- =============================================================================
-- END OF SCHEMA
-- =============================================================================
